backend:
  name: github
  repo: Barakhov/artiteatre.studio #replace new repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/assets
public_folder: /assets
site_url: "https://artiteatre.studio/" # site name name here

collections:
  - name: inicio
    label: Inicio
    folder: src/content/inicio
    format: frontmatter
    fields:
      - { label: Titulo, name: title, widget: string }
      - { label: Introduccion, name: intro, widget: markdown }
      - { label: Descripcion, name: description, widget: markdown }
  - name: verano
    label: Verano
    files:
      - name: intro
        label: "Introducción"
        file: src/content/verano/intro.md
        fields:
          - { label: Titulo, name: title, widget: string }
          - { label: Introduccion, name: intro, widget: markdown }
      - name: profesorado
        label: "Profesorado"
        file: src/content/verano/profesorado.md
        fields:
          - { label: Titulo, name: title, widget: string }
          - label: "Profesoras/es"
            name: teachers
            widget: list
            fields:
              - { label: "Nombre", name: name, widget: string, required: true }
              - { label: "Imagen", name: image, widget: image, required: true }
              - {
                  label: "Texto alternativo/descriptivo para la imagen",
                  name: image_alt,
                  widget: string,
                  required: true,
                }
              - {
                  label: "Biografía",
                  name: description,
                  widget: markdown,
                  required: true,
                }
      - name: descargas
        label: "Docs. para descargar"
        file: src/content/verano/descargas.md
        fields:
          - { label: Titulo, name: title, widget: string }
          - label: "Documentos para descargar"
            name: documents
            widget: list
            fields:
              - { label: "Nombre", name: name, widget: string, required: true }
              - { label: "Documento", name: doc, widget: file, required: true }
      - name: materias
        label: "Materias"
        file: src/content/verano/materias.md
        fields:
          - { label: "Título", name: "title", widget: "string", required: true }
          - label: "Materias"
            name: "materias"
            widget: "list"
            fields:
              - {
                  label: "Título",
                  name: "title",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "Imagen",
                  name: "image",
                  widget: "image",
                  required: true,
                }
              - {
                  label: "Texto",
                  name: "text",
                  widget: "markdown",
                  required: true,
                }
              - {
                  label: "Enlace",
                  name: "link",
                  widget: "file",
                  required: true,
                }
      - name: galeria
        label: "Galería"
        file: src/content/verano/galeria.md
        fields:
          - { label: "Título", name: "title", widget: "string", required: true }
          - label: "Imágenes"
            name: "images"
            widget: "list"
            fields:
              - {
                  label: "Imagen",
                  name: "image",
                  widget: "image",
                  required: true,
                }
              - {
                  label: "Pie de foto",
                  name: "caption",
                  widget: "string",
                  required: true,
                }
  # - name: post
  #   label: Posts
  #   folder: src/content/posts
  #   create: true
  #   format: frontmatter
  #   preview_path: post/{{slug}}
  #   fields:
  #     - { name: title, label: Title }
  #     - { name: description, label: Description }
  #     - { name: publishedAt, label: Date, widget: date }
  #     - {
  #         label: "Publish",
  #         name: "isPublish",
  #         widget: "boolean",
  #         default: true,
  #       }
  #     - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
  #     - { name: body, label: Body, widget: markdown }
