backend:
  name: github
  repo: Barakhov/artiteatre.studio #replace new repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://aesthetic-elf-c76dc5.netlify.app/" # site name name here

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - name: inicio
        label: Inicio
        file: src/content/pages/inicio.yml
        fields:
          - { label: Titulo, name: title, widget: string }
          - { label: Introduccion, name: intro, widget: markdown }
          - { label: Descripcion, name: description, widget: markdown }
